name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build Stage
      run: |
        echo "Building application..."

    - name: Test Stage
      run: |
        python app.py

    - name: Deploy Stage
      run: |
        echo "Deploying application..."
